"""Type stubs for the `epicsrs._epicsrs` extension.

Hand-written from the pyo3 surface in `src/`; `tests/test_stubs.py`
checks every name, member and parameter list against the built module.
"""

from collections.abc import Awaitable, Iterator, Mapping, Sequence
from typing import Any, ClassVar

__version__: str

def ca_message(status: int) -> str: ...

# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class CaError(Exception):
    """Channel Access operation failed; args are (message, eca_status)."""

    @property
    def status(self) -> int: ...

class CaTimeout(CaError): ...
class CaDisconnected(CaError): ...

class PvaError(Exception): ...
class PvaTimeout(PvaError): ...
class PvaDisconnected(PvaError): ...
class PvaRemoteError(PvaError): ...

# ---------------------------------------------------------------------------
# Channel Access
# ---------------------------------------------------------------------------

class Snapshot:
    """One value read from a channel, with the metadata of its DBR class."""

    @property
    def name(self) -> str: ...
    @property
    def value(self) -> Any: ...
    @property
    def datatype(self) -> str: ...
    @property
    def dbr(self) -> int: ...
    @property
    def element_count(self) -> int: ...
    @property
    def status(self) -> int: ...
    @property
    def severity(self) -> int: ...
    @property
    def raw_stamp(self) -> tuple[int, int]: ...
    @property
    def units(self) -> str | None: ...
    @property
    def precision(self) -> int | None: ...
    @property
    def upper_disp_limit(self) -> float | None: ...
    @property
    def lower_disp_limit(self) -> float | None: ...
    @property
    def upper_alarm_limit(self) -> float | None: ...
    @property
    def lower_alarm_limit(self) -> float | None: ...
    @property
    def upper_warning_limit(self) -> float | None: ...
    @property
    def lower_warning_limit(self) -> float | None: ...
    @property
    def upper_ctrl_limit(self) -> float | None: ...
    @property
    def lower_ctrl_limit(self) -> float | None: ...
    @property
    def enums(self) -> list[str] | None: ...
    @property
    def ackt(self) -> int | None: ...
    @property
    def acks(self) -> int | None: ...
    @property
    def timestamp(self) -> float: ...
    def __repr__(self) -> str: ...

class ChannelInfo:
    @property
    def name(self) -> str: ...
    @property
    def host(self) -> str: ...
    @property
    def datatype(self) -> str: ...
    @property
    def dbr(self) -> int: ...
    @property
    def element_count(self) -> int: ...
    @property
    def read_access(self) -> bool: ...
    @property
    def write_access(self) -> bool: ...

class ConnectionEvent:
    @property
    def kind(self) -> str: ...
    @property
    def read(self) -> bool | None: ...
    @property
    def write(self) -> bool | None: ...
    @property
    def dbr(self) -> int | None: ...
    def __repr__(self) -> str: ...

class CaEvents:
    def recv(self, timeout: float | None = None) -> ConnectionEvent | None: ...
    def recv_async(self, timeout: float | None = None) -> Awaitable[ConnectionEvent | None]: ...
    def close(self) -> None: ...

class CaChannel:
    @property
    def name(self) -> str: ...
    @property
    def connected(self) -> bool: ...
    @property
    def dbr(self) -> int | None: ...
    @property
    def element_count(self) -> int | None: ...
    def info(self) -> ChannelInfo: ...
    def wait_connected(self, timeout: float | None = None) -> None: ...
    def wait_connected_async(self, timeout: float | None = None) -> Awaitable[None]: ...
    def get(
        self,
        dbr: int | None = None,
        form: int = 0,
        enum_as_string: bool = False,
        count: int = 0,
        timeout: float | None = None,
    ) -> Snapshot: ...
    def get_async(
        self,
        dbr: int | None = None,
        form: int = 0,
        enum_as_string: bool = False,
        count: int = 0,
        timeout: float | None = None,
    ) -> Awaitable[Snapshot]: ...
    def put(self, value: Any, wait: bool = True, timeout: float | None = None) -> None: ...
    def put_async(self, value: Any, wait: bool = True, timeout: float | None = None) -> Awaitable[None]: ...
    def subscribe(
        self,
        deadband: float = 0.0,
        mask: int | None = None,
        enum_as_string: bool = False,
        float_as_string: bool = False,
        count: int = 0,
    ) -> CaSubscription: ...
    def subscribe_async(
        self,
        deadband: float = 0.0,
        mask: int | None = None,
        enum_as_string: bool = False,
        float_as_string: bool = False,
        count: int = 0,
    ) -> Awaitable[CaSubscription]: ...
    def events(self) -> CaEvents: ...
    def __repr__(self) -> str: ...

class CaSubscription:
    @property
    def name(self) -> str: ...
    def recv(self, timeout: float | None = None) -> Snapshot | None: ...
    def recv_async(self, timeout: float | None = None) -> Awaitable[Snapshot | None]: ...
    def recv_batch(self, max_items: int = 0, timeout: float | None = None) -> list[Snapshot] | None: ...
    def recv_batch_async(
        self, max_items: int = 0, timeout: float | None = None
    ) -> Awaitable[list[Snapshot] | None]: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def close(self) -> None: ...
    def close_async(self) -> Awaitable[None]: ...
    def __enter__(self) -> CaSubscription: ...
    def __exit__(self, _exc_type: object, _exc_value: object, _traceback: object) -> None: ...

class CaContext:
    def __init__(self) -> None: ...
    def channel(self, name: str) -> CaChannel: ...
    def close(self) -> None: ...
    def connection_count(self) -> int: ...
    def wait_connected_many(
        self, channels: Sequence[CaChannel], timeout: float | None = None
    ) -> list[BaseException | None]: ...
    def wait_connected_many_async(
        self, channels: Sequence[CaChannel], timeout: float | None = None
    ) -> Awaitable[list[BaseException | None]]: ...
    def get_many(
        self,
        channels: Sequence[CaChannel],
        dbr: int | None = None,
        form: int = 0,
        enum_as_string: bool = False,
        count: int = 0,
        timeout: float | None = None,
    ) -> list[Snapshot | BaseException]: ...
    def get_many_async(
        self,
        channels: Sequence[CaChannel],
        dbr: int | None = None,
        form: int = 0,
        enum_as_string: bool = False,
        count: int = 0,
        timeout: float | None = None,
    ) -> Awaitable[list[Snapshot | BaseException]]: ...
    def put_many(
        self,
        channels: Sequence[CaChannel],
        values: Sequence[Any],
        wait: bool = True,
        timeout: float | None = None,
    ) -> list[BaseException | None]: ...
    def put_many_async(
        self,
        channels: Sequence[CaChannel],
        values: Sequence[Any],
        wait: bool = True,
        timeout: float | None = None,
    ) -> Awaitable[list[BaseException | None]]: ...

class MonitorHub:
    """One queue fed by every CA subscription opened through it.

    `recv_batch` items are `(id, kind, payload)`: kind 0 a `Snapshot`, 1 an
    exception, 2/3/4/5 (`None`) connect-timeout, connected, end,
    disconnected, 6 an access-rights `(read, write)` pair.
    """

    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def subscribe(
        self,
        channel: CaChannel,
        deadband: float = 0.0,
        mask: int | None = None,
        enum_as_string: bool = False,
        float_as_string: bool = False,
        count: int = 0,
        connect_timeout: float | None = None,
        values: bool = True,
        values_max_count: int | None = None,
    ) -> int: ...
    def close_subscription(self, id: int) -> None: ...
    def pause(self, id: int) -> None: ...
    def resume(self, id: int) -> None: ...
    def recv_batch(
        self, max_items: int = 0, timeout: float | None = None
    ) -> list[tuple[int, int, Any]] | None: ...
    def recv_batch_async(
        self, max_items: int = 0, timeout: float | None = None
    ) -> Awaitable[list[tuple[int, int, Any]] | None]: ...
    def close(self) -> None: ...

# ---------------------------------------------------------------------------
# pvAccess: data
# ---------------------------------------------------------------------------

class Type:
    """A pvData structure type. `spec` is a list of `(name, code)` members."""

    __hash__: ClassVar[None]  # type: ignore[assignment]

    def __init__(self, spec: Any, id: str | None = None) -> None: ...
    def getID(self) -> str: ...
    def keys(self) -> list[str]: ...
    def items(self) -> list[tuple[str, Any]]: ...
    def has(self, key: str) -> bool: ...
    def aspy(self) -> Any: ...
    def __call__(self, initial: Any = None) -> Value: ...
    def __contains__(self, key: str) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __eq__(self, value: object) -> bool: ...
    def __repr__(self) -> str: ...

class Value:
    """A pvData structure value with its change marks."""

    def __init__(self, type: Type | Any, initial: Any = None) -> None: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def has(self, key: str) -> bool: ...
    def keys(self) -> list[str]: ...
    def items(self) -> list[tuple[str, Any]]: ...
    def getID(self) -> str: ...
    def type(self, field: str | None = None) -> Any: ...
    def changed(self, *fields: str) -> bool: ...
    def changedSet(self, expand: bool = False, parents: bool = False) -> set[str]: ...
    def mark(self, field: str | None = None, val: bool = True) -> None: ...
    def unmark(self, field: str | None = None) -> None: ...
    def select(self, field: str, selector: str | None = None) -> None: ...
    def todict(self, fields: Sequence[str] | None = None) -> dict[str, Any]: ...
    def tolist(self) -> list[tuple[str, Any]]: ...
    def tostr(self) -> str: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

# ---------------------------------------------------------------------------
# pvAccess: client
# ---------------------------------------------------------------------------

class PvaContext:
    def __init__(self, conf: Mapping[str, str] | None = None) -> None: ...
    def get(self, name: str, request: str | None = None, timeout: float | None = None) -> Value: ...
    def get_async(
        self, name: str, request: str | None = None, timeout: float | None = None
    ) -> Awaitable[Value]: ...
    def get_many(
        self, names: Sequence[str], requests: Sequence[str | None], timeout: float | None = None
    ) -> list[Value | BaseException]: ...
    def put_begin_many(
        self,
        names: Sequence[str],
        requests: Sequence[str | None],
        fetch: Sequence[bool],
        timeout: float | None = None,
    ) -> list[PutOp | BaseException]: ...
    def put_commit_many(
        self, ops: Sequence[PutOp], values: Sequence[Value], timeout: float | None = None
    ) -> list[BaseException | None]: ...
    def info(self, name: str, timeout: float | None = None) -> Type: ...
    def info_async(self, name: str, timeout: float | None = None) -> Awaitable[Type]: ...
    def put_begin_async(
        self, name: str, request: str | None = None, fetch: bool = True, timeout: float | None = None
    ) -> Awaitable[PutOp]: ...
    def rpc(
        self, name: str, value: Value, request: str | None = None, timeout: float | None = None
    ) -> Value | None: ...
    def rpc_async(
        self, name: str, value: Value, request: str | None = None, timeout: float | None = None
    ) -> Awaitable[Value | None]: ...
    def connect(self, name: str, timeout: float | None = None) -> str: ...
    def connect_async(self, name: str, timeout: float | None = None) -> Awaitable[str]: ...
    def close(self) -> None: ...

class PutOp:
    """A put between its two phases: opened on the server (its type known,
    the current value read on the same operation when begun with `fetch`)
    and not yet committed. Dropped uncommitted, it is destroyed.
    """

    @property
    def type(self) -> Type: ...
    def current(self) -> Value | None: ...
    def commit_async(self, value: Value, timeout: float | None = None) -> Awaitable[None]: ...

class PvaMonitorHub:
    """One queue fed by every PVA monitor opened through it.

    `recv_batch` items are `(id, kind, payload)`: kind 0 a `Value`, 1 the
    server address the monitor connected to, 2/3 (`None`) disconnected /
    finished.
    """

    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def subscribe(
        self, context: PvaContext, name: str, request: str | None = None, limit: int | None = None
    ) -> int: ...
    def close_subscription(self, id: int) -> None: ...
    def pause(self, id: int) -> None: ...
    def resume(self, id: int) -> None: ...
    def recv_batch(self, timeout: float | None = None) -> list[tuple[int, int, Any]] | None: ...
    def recv_batch_async(
        self, timeout: float | None = None
    ) -> Awaitable[list[tuple[int, int, Any]] | None]: ...
    def close(self) -> None: ...

# ---------------------------------------------------------------------------
# pvAccess: server
# ---------------------------------------------------------------------------

class ServerOperation:
    """A PUT or RPC a client sent to a `PvaSharedPV`; finish it with `done`."""

    def kind(self) -> str: ...
    def name(self) -> str: ...
    def peer(self) -> str: ...
    def account(self) -> str: ...
    def method(self) -> str: ...
    def value(self) -> Value: ...
    def pvRequest(self) -> Value | None: ...
    def done(self, value: Value | None = None, error: str | None = None) -> None: ...

class PvaWorkQueue:
    """Events for the PVs attached to it: `(token, kind, op)` with kind
    `"put"` / `"rpc"` (op set) or `"first"` / `"last"` (op `None`)."""

    def __init__(self) -> None: ...
    def recv(self) -> tuple[Any, str, ServerOperation | None] | None: ...
    def recv_async(self) -> Awaitable[tuple[Any, str, ServerOperation | None] | None]: ...
    def stop(self) -> None: ...

class PvaSharedPV:
    def __init__(self, queue: PvaWorkQueue, token: Any) -> None: ...
    def open(self, value: Value) -> None: ...
    def close(self) -> None: ...
    def isOpen(self) -> bool: ...
    def post(self, value: Value) -> None: ...
    def current(self) -> Value | None: ...
    def type(self) -> Type | None: ...

class PvaProvider:
    def __init__(self, name: str) -> None: ...
    def name(self) -> str: ...
    def add(self, name: str, pv: PvaSharedPV) -> None: ...
    def remove(self, name: str) -> bool: ...
    def keys(self) -> list[str]: ...

class PvaServer:
    def __init__(
        self,
        providers: Sequence[tuple[PvaProvider, int]],
        conf: Mapping[str, str] | None = None,
        useenv: bool = True,
        isolate: bool = False,
    ) -> None: ...
    def stop(self) -> None: ...
    def running(self) -> bool: ...
    def tcp_port(self) -> int: ...
    def udp_port(self) -> int: ...
    def conf(self) -> dict[str, str]: ...
